-- MySQL Script generated by MySQL Workbench
-- Mon Mar  3 14:24:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Edufast
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Edufast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Edufast` DEFAULT CHARACTER SET utf8 ;
USE `Edufast` ;

-- -----------------------------------------------------
-- Table `Edufast`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `rol` CHAR(15) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`jornada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`jornada` (
  `id_jornada` INT NOT NULL AUTO_INCREMENT,
  `jornada` CHAR(20) NULL,
  `hora_inicio` TIME NULL,
  `hora_final` TIME NULL,
  PRIMARY KEY (`id_jornada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`registro` (
  `num_doc` INT NOT NULL,
  `tipo_doc` CHAR(15) NULL,
  `foto_perfil` LONGBLOB NULL,
  `nombres` CHAR(45) NULL,
  `apellidos` CHAR(45) NULL,
  `cel` CHAR(12) NULL,
  `telefono` CHAR(15) NULL,
  `direccion` CHAR(45) NULL,
  `correo` CHAR(45) NULL,
  `contraseña` CHAR(200) NULL,
  `rol_id_rol` INT NOT NULL,
  `jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`num_doc`, `rol_id_rol`, `jornada_id_jornada`),
  INDEX `fk_registro_rol1_idx` (`rol_id_rol` ASC) ,
  INDEX `fk_registro_jornada1_idx` (`jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_registro_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `Edufast`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_jornada1`
    FOREIGN KEY (`jornada_id_jornada`)
    REFERENCES `Edufast`.`jornada` (`id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`public_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`public_eventos` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `img` LONGBLOB NULL,
  `evento` VARCHAR(255) NULL,
  `fecha_evento` DATE NULL,
  `registro_num_doc` INT NOT NULL,
  PRIMARY KEY (`id_evento`, `registro_num_doc`),
  INDEX `fk_public_eventos_registro_idx` (`registro_num_doc` ASC) ,
  CONSTRAINT `fk_public_eventos_registro`
    FOREIGN KEY (`registro_num_doc`)
    REFERENCES `Edufast`.`registro` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`public_noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`public_noticias` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` CHAR(100) NULL,
  `info` VARCHAR(255) NULL,
  `registro_num_doc` INT NOT NULL,
  PRIMARY KEY (`id_noticia`, `registro_num_doc`),
  INDEX `fk_public_noticias_registro1_idx` (`registro_num_doc` ASC) ,
  CONSTRAINT `fk_public_noticias_registro1`
    FOREIGN KEY (`registro_num_doc`)
    REFERENCES `Edufast`.`registro` (`num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`estudiante` (
  `id_estudiante` INT NOT NULL,
  `sexo` CHAR(10) NULL,
  `fecha_nacimientol` DATE NULL,
  `Eps` VARCHAR(45) NULL,
  `RH` CHAR(10) NULL,
  `NIvel educativo` CHAR(45) NULL,
  `Estado` CHAR(25) NULL,
  `registro_num_doc` INT NOT NULL,
  `registro_rol_id_rol` INT NOT NULL,
  `registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `registro_num_doc`, `registro_rol_id_rol`, `registro_jornada_id_jornada`),
  INDEX `fk_estudiante_registro1_idx` (`registro_num_doc` ASC, `registro_rol_id_rol` ASC, `registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_estudiante_registro1`
    FOREIGN KEY (`registro_num_doc` , `registro_rol_id_rol` , `registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`registro` (`num_doc` , `rol_id_rol` , `jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`grado` (
  `id_grado` INT NOT NULL AUTO_INCREMENT,
  `nivel_educativo` CHAR(45) NULL,
  `grado` CHAR(10) NULL,
  PRIMARY KEY (`id_grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`cursos` (
  `id_cursos` INT NOT NULL AUTO_INCREMENT,
  `curso` CHAR(10) NULL,
  `grado_id_grado` INT NOT NULL,
  PRIMARY KEY (`id_cursos`, `grado_id_grado`),
  INDEX `fk_cursos_grado1_idx` (`grado_id_grado` ASC) ,
  CONSTRAINT `fk_cursos_grado1`
    FOREIGN KEY (`grado_id_grado`)
    REFERENCES `Edufast`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`docente` (
  `id_docente` INT NOT NULL AUTO_INCREMENT,
  `profesion` CHAR(45) NULL,
  `cursos_id_cursos` INT NOT NULL,
  `cursos_grado_id_grado` INT NOT NULL,
  `registro_num_doc` INT NOT NULL,
  `registro_rol_id_rol` INT NOT NULL,
  `registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`id_docente`, `cursos_id_cursos`, `cursos_grado_id_grado`, `registro_num_doc`, `registro_rol_id_rol`, `registro_jornada_id_jornada`),
  INDEX `fk_docente_cursos1_idx` (`cursos_id_cursos` ASC, `cursos_grado_id_grado` ASC) ,
  INDEX `fk_docente_registro1_idx` (`registro_num_doc` ASC, `registro_rol_id_rol` ASC, `registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_docente_cursos1`
    FOREIGN KEY (`cursos_id_cursos` , `cursos_grado_id_grado`)
    REFERENCES `Edufast`.`cursos` (`id_cursos` , `grado_id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_registro1`
    FOREIGN KEY (`registro_num_doc` , `registro_rol_id_rol` , `registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`registro` (`num_doc` , `rol_id_rol` , `jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `nombre_area` CHAR(45) NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `materia` CHAR(45) NULL,
  `grado_id_grado` INT NOT NULL,
  `area_id_area` INT NOT NULL,
  PRIMARY KEY (`id_materia`, `grado_id_grado`, `area_id_area`),
  INDEX `fk_materia_grado1_idx` (`grado_id_grado` ASC) ,
  INDEX `fk_materia_area1_idx` (`area_id_area` ASC) ,
  CONSTRAINT `fk_materia_grado1`
    FOREIGN KEY (`grado_id_grado`)
    REFERENCES `Edufast`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_area1`
    FOREIGN KEY (`area_id_area`)
    REFERENCES `Edufast`.`area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`logro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`logro` (
  `id_logro` INT NOT NULL,
  `nombre_logro` CHAR(100) NULL,
  `descripcion_logro` CHAR(200) NULL,
  `materia_id_materia` INT NOT NULL,
  `materia_grado_id_grado` INT NOT NULL,
  `materia_area_id_area` INT NOT NULL,
  PRIMARY KEY (`id_logro`, `materia_id_materia`, `materia_grado_id_grado`, `materia_area_id_area`),
  INDEX `fk_logro_materia1_idx` (`materia_id_materia` ASC, `materia_grado_id_grado` ASC, `materia_area_id_area` ASC) ,
  CONSTRAINT `fk_logro_materia1`
    FOREIGN KEY (`materia_id_materia` , `materia_grado_id_grado` , `materia_area_id_area`)
    REFERENCES `Edufast`.`materia` (`id_materia` , `grado_id_grado` , `area_id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`actividad` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `nombre_act` CHAR(100) NULL,
  `descripcion` VARCHAR(100) NULL,
  `fecha_entrega` DATE NULL,
  `logro_id_logro` INT NOT NULL,
  `logro_materia_id_materia` INT NOT NULL,
  `logro_materia_grado_id_grado` INT NOT NULL,
  `logro_materia_area_id_area` INT NOT NULL,
  `docente_id_docente` INT NOT NULL,
  `docente_cursos_id_cursos` INT NOT NULL,
  `docente_cursos_grado_id_grado` INT NOT NULL,
  `docente_registro_num_doc` INT NOT NULL,
  `docente_registro_rol_id_rol` INT NOT NULL,
  `docente_registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`id_actividad`, `logro_id_logro`, `logro_materia_id_materia`, `logro_materia_grado_id_grado`, `logro_materia_area_id_area`, `docente_id_docente`, `docente_cursos_id_cursos`, `docente_cursos_grado_id_grado`, `docente_registro_num_doc`, `docente_registro_rol_id_rol`, `docente_registro_jornada_id_jornada`),
  INDEX `fk_actividad_logro1_idx` (`logro_id_logro` ASC, `logro_materia_id_materia` ASC, `logro_materia_grado_id_grado` ASC, `logro_materia_area_id_area` ASC) ,
  INDEX `fk_actividad_docente1_idx` (`docente_id_docente` ASC, `docente_cursos_id_cursos` ASC, `docente_cursos_grado_id_grado` ASC, `docente_registro_num_doc` ASC, `docente_registro_rol_id_rol` ASC, `docente_registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_actividad_logro1`
    FOREIGN KEY (`logro_id_logro` , `logro_materia_id_materia` , `logro_materia_grado_id_grado` , `logro_materia_area_id_area`)
    REFERENCES `Edufast`.`logro` (`id_logro` , `materia_id_materia` , `materia_grado_id_grado` , `materia_area_id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_docente1`
    FOREIGN KEY (`docente_id_docente` , `docente_cursos_id_cursos` , `docente_cursos_grado_id_grado` , `docente_registro_num_doc` , `docente_registro_rol_id_rol` , `docente_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`docente` (`id_docente` , `cursos_id_cursos` , `cursos_grado_id_grado` , `registro_num_doc` , `registro_rol_id_rol` , `registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`observador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`observador` (
  `id_observador` INT NOT NULL AUTO_INCREMENT,
  `fecha_ob` DATE NULL,
  `comentario` CHAR(200) NULL,
  `Tel_emergencia` CHAR(25) NULL,
  `padre_nombre` CHAR(90) NULL,
  `padre_apellido` CHAR(90) NULL,
  `padre_ocupacion` CHAR(150) NULL,
  `padre_cedula` CHAR(15) NULL,
  `padre_direccion` VARCHAR(260) NULL,
  `padre_telefono` CHAR(13) NULL,
  `padre_correo` CHAR(200) NULL,
  `madre_nombre` CHAR(90) NULL,
  `madre_apellido` CHAR(90) NULL,
  `madre_ocupacion` CHAR(150) NULL,
  `madre_cedula` CHAR(15) NULL,
  `madre_direccion` VARCHAR(260) NULL,
  `madre_telefono` CHAR(13) NULL,
  `madre_correo` CHAR(200) NULL,
  `acudiente_nombre` CHAR(90) NULL,
  `acudiente_apellido` CHAR(90) NULL,
  `acudiente_ocupacion` CHAR(150) NULL,
  `acudiente_cedula` CHAR(15) NULL,
  `acudiente_direccion` VARCHAR(260) NULL,
  `acudiente_telefono` CHAR(13) NULL,
  `acudiente_correo` CHAR(200) NULL,
  PRIMARY KEY (`id_observador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`boletin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`boletin` (
  `id_boletin` INT NOT NULL AUTO_INCREMENT,
  `periodo` CHAR(10) NULL,
  `puesto` CHAR(10) NULL,
  `observador_id_observador` INT NOT NULL,
  PRIMARY KEY (`id_boletin`, `observador_id_observador`),
  INDEX `fk_boletin_observador1_idx` (`observador_id_observador` ASC) ,
  CONSTRAINT `fk_boletin_observador1`
    FOREIGN KEY (`observador_id_observador`)
    REFERENCES `Edufast`.`observador` (`id_observador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `grado_id_grado` INT NOT NULL,
  `cursos_id_cursos` INT NOT NULL,
  `estudiante_id_estudiante` INT NOT NULL,
  `estudiante_registro_num_doc` INT NOT NULL,
  `estudiante_registro_rol_id_rol` INT NOT NULL,
  `estudiante_registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`id_matricula`, `grado_id_grado`, `cursos_id_cursos`, `estudiante_id_estudiante`, `estudiante_registro_num_doc`, `estudiante_registro_rol_id_rol`, `estudiante_registro_jornada_id_jornada`),
  INDEX `fk_matricula_grado1_idx` (`grado_id_grado` ASC) ,
  INDEX `fk_matricula_cursos1_idx` (`cursos_id_cursos` ASC) ,
  INDEX `fk_matricula_estudiante1_idx` (`estudiante_id_estudiante` ASC, `estudiante_registro_num_doc` ASC, `estudiante_registro_rol_id_rol` ASC, `estudiante_registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_matricula_grado1`
    FOREIGN KEY (`grado_id_grado`)
    REFERENCES `Edufast`.`grado` (`id_grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_cursos1`
    FOREIGN KEY (`cursos_id_cursos`)
    REFERENCES `Edufast`.`cursos` (`id_cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_estudiante1`
    FOREIGN KEY (`estudiante_id_estudiante` , `estudiante_registro_num_doc` , `estudiante_registro_rol_id_rol` , `estudiante_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`estudiante` (`id_estudiante` , `registro_num_doc` , `registro_rol_id_rol` , `registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`nota` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `fecha_nota` DATE NULL,
  `nota` DECIMAL(10) NULL,
  `boletin_id_boletin` INT NOT NULL,
  `matricula_id_matricula` INT NOT NULL,
  `matricula_grado_id_grado` INT NOT NULL,
  `matricula_cursos_id_cursos` INT NOT NULL,
  `matricula_estudiante_id_estudiante` INT NOT NULL,
  `matricula_estudiante_registro_num_doc` INT NOT NULL,
  `matricula_estudiante_registro_rol_id_rol` INT NOT NULL,
  `matricula_estudiante_registro_jornada_id_jornada` INT NOT NULL,
  `actividad_id_actividad` INT NOT NULL,
  `actividad_logro_id_logro` INT NOT NULL,
  `actividad_logro_materia_id_materia` INT NOT NULL,
  `actividad_logro_materia_grado_id_grado` INT NOT NULL,
  `actividad_logro_materia_area_id_area` INT NOT NULL,
  `actividad_docente_id_docente` INT NOT NULL,
  `actividad_docente_cursos_id_cursos` INT NOT NULL,
  `actividad_docente_cursos_grado_id_grado` INT NOT NULL,
  `actividad_docente_registro_num_doc` INT NOT NULL,
  `actividad_docente_registro_rol_id_rol` INT NOT NULL,
  `actividad_docente_registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`id_nota`, `boletin_id_boletin`, `matricula_id_matricula`, `matricula_grado_id_grado`, `matricula_cursos_id_cursos`, `matricula_estudiante_id_estudiante`, `matricula_estudiante_registro_num_doc`, `matricula_estudiante_registro_rol_id_rol`, `matricula_estudiante_registro_jornada_id_jornada`, `actividad_id_actividad`, `actividad_logro_id_logro`, `actividad_logro_materia_id_materia`, `actividad_logro_materia_grado_id_grado`, `actividad_logro_materia_area_id_area`, `actividad_docente_id_docente`, `actividad_docente_cursos_id_cursos`, `actividad_docente_cursos_grado_id_grado`, `actividad_docente_registro_num_doc`, `actividad_docente_registro_rol_id_rol`, `actividad_docente_registro_jornada_id_jornada`),
  INDEX `fk_nota_boletin1_idx` (`boletin_id_boletin` ASC) ,
  INDEX `fk_nota_matricula1_idx` (`matricula_id_matricula` ASC, `matricula_grado_id_grado` ASC, `matricula_cursos_id_cursos` ASC, `matricula_estudiante_id_estudiante` ASC, `matricula_estudiante_registro_num_doc` ASC, `matricula_estudiante_registro_rol_id_rol` ASC, `matricula_estudiante_registro_jornada_id_jornada` ASC) ,
  INDEX `fk_nota_actividad1_idx` (`actividad_id_actividad` ASC, `actividad_logro_id_logro` ASC, `actividad_logro_materia_id_materia` ASC, `actividad_logro_materia_grado_id_grado` ASC, `actividad_logro_materia_area_id_area` ASC, `actividad_docente_id_docente` ASC, `actividad_docente_cursos_id_cursos` ASC, `actividad_docente_cursos_grado_id_grado` ASC, `actividad_docente_registro_num_doc` ASC, `actividad_docente_registro_rol_id_rol` ASC, `actividad_docente_registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_nota_boletin1`
    FOREIGN KEY (`boletin_id_boletin`)
    REFERENCES `Edufast`.`boletin` (`id_boletin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_matricula1`
    FOREIGN KEY (`matricula_id_matricula` , `matricula_grado_id_grado` , `matricula_cursos_id_cursos` , `matricula_estudiante_id_estudiante` , `matricula_estudiante_registro_num_doc` , `matricula_estudiante_registro_rol_id_rol` , `matricula_estudiante_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`matricula` (`id_matricula` , `grado_id_grado` , `cursos_id_cursos` , `estudiante_id_estudiante` , `estudiante_registro_num_doc` , `estudiante_registro_rol_id_rol` , `estudiante_registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_actividad1`
    FOREIGN KEY (`actividad_id_actividad` , `actividad_logro_id_logro` , `actividad_logro_materia_id_materia` , `actividad_logro_materia_grado_id_grado` , `actividad_logro_materia_area_id_area` , `actividad_docente_id_docente` , `actividad_docente_cursos_id_cursos` , `actividad_docente_cursos_grado_id_grado` , `actividad_docente_registro_num_doc` , `actividad_docente_registro_rol_id_rol` , `actividad_docente_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`actividad` (`id_actividad` , `logro_id_logro` , `logro_materia_id_materia` , `logro_materia_grado_id_grado` , `logro_materia_area_id_area` , `docente_id_docente` , `docente_cursos_id_cursos` , `docente_cursos_grado_id_grado` , `docente_registro_num_doc` , `docente_registro_rol_id_rol` , `docente_registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`Asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`Asistencia` (
  `idAsistencia` INT NOT NULL,
  `fecha_asistencia` DATE NULL,
  `asistencia` CHAR(10) NULL,
  `matricula_id_matricula` INT NOT NULL,
  `matricula_grado_id_grado` INT NOT NULL,
  `matricula_cursos_id_cursos` INT NOT NULL,
  `matricula_estudiante_id_estudiante` INT NOT NULL,
  `matricula_estudiante_registro_num_doc` INT NOT NULL,
  `matricula_estudiante_registro_rol_id_rol` INT NOT NULL,
  `matricula_estudiante_registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`idAsistencia`, `matricula_id_matricula`, `matricula_grado_id_grado`, `matricula_cursos_id_cursos`, `matricula_estudiante_id_estudiante`, `matricula_estudiante_registro_num_doc`, `matricula_estudiante_registro_rol_id_rol`, `matricula_estudiante_registro_jornada_id_jornada`),
  INDEX `fk_Asistencia_matricula1_idx` (`matricula_id_matricula` ASC, `matricula_grado_id_grado` ASC, `matricula_cursos_id_cursos` ASC, `matricula_estudiante_id_estudiante` ASC, `matricula_estudiante_registro_num_doc` ASC, `matricula_estudiante_registro_rol_id_rol` ASC, `matricula_estudiante_registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_Asistencia_matricula1`
    FOREIGN KEY (`matricula_id_matricula` , `matricula_grado_id_grado` , `matricula_cursos_id_cursos` , `matricula_estudiante_id_estudiante` , `matricula_estudiante_registro_num_doc` , `matricula_estudiante_registro_rol_id_rol` , `matricula_estudiante_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`matricula` (`id_matricula` , `grado_id_grado` , `cursos_id_cursos` , `estudiante_id_estudiante` , `estudiante_registro_num_doc` , `estudiante_registro_rol_id_rol` , `estudiante_registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`observador_has_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`observador_has_estudiante` (
  `observador_id_observador` INT NOT NULL,
  `estudiante_id_estudiante` INT NOT NULL,
  `estudiante_registro_num_doc` INT NOT NULL,
  `estudiante_registro_rol_id_rol` INT NOT NULL,
  `estudiante_registro_jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`observador_id_observador`, `estudiante_id_estudiante`, `estudiante_registro_num_doc`, `estudiante_registro_rol_id_rol`, `estudiante_registro_jornada_id_jornada`),
  INDEX `fk_observador_has_estudiante_estudiante1_idx` (`estudiante_id_estudiante` ASC, `estudiante_registro_num_doc` ASC, `estudiante_registro_rol_id_rol` ASC, `estudiante_registro_jornada_id_jornada` ASC) ,
  INDEX `fk_observador_has_estudiante_observador1_idx` (`observador_id_observador` ASC) ,
  CONSTRAINT `fk_observador_has_estudiante_observador1`
    FOREIGN KEY (`observador_id_observador`)
    REFERENCES `Edufast`.`observador` (`id_observador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observador_has_estudiante_estudiante1`
    FOREIGN KEY (`estudiante_id_estudiante` , `estudiante_registro_num_doc` , `estudiante_registro_rol_id_rol` , `estudiante_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`estudiante` (`id_estudiante` , `registro_num_doc` , `registro_rol_id_rol` , `registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Edufast`.`docente_has_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Edufast`.`docente_has_materia` (
  `docente_id_docente` INT NOT NULL,
  `docente_cursos_id_cursos` INT NOT NULL,
  `docente_cursos_grado_id_grado` INT NOT NULL,
  `docente_registro_num_doc` INT NOT NULL,
  `docente_registro_rol_id_rol` INT NOT NULL,
  `docente_registro_jornada_id_jornada` INT NOT NULL,
  `materia_id_materia` INT NOT NULL,
  `materia_grado_id_grado` INT NOT NULL,
  `materia_area_id_area` INT NOT NULL,
  PRIMARY KEY (`docente_id_docente`, `docente_cursos_id_cursos`, `docente_cursos_grado_id_grado`, `docente_registro_num_doc`, `docente_registro_rol_id_rol`, `docente_registro_jornada_id_jornada`, `materia_id_materia`, `materia_grado_id_grado`, `materia_area_id_area`),
  INDEX `fk_docente_has_materia_materia1_idx` (`materia_id_materia` ASC, `materia_grado_id_grado` ASC, `materia_area_id_area` ASC) ,
  INDEX `fk_docente_has_materia_docente1_idx` (`docente_id_docente` ASC, `docente_cursos_id_cursos` ASC, `docente_cursos_grado_id_grado` ASC, `docente_registro_num_doc` ASC, `docente_registro_rol_id_rol` ASC, `docente_registro_jornada_id_jornada` ASC) ,
  CONSTRAINT `fk_docente_has_materia_docente1`
    FOREIGN KEY (`docente_id_docente` , `docente_cursos_id_cursos` , `docente_cursos_grado_id_grado` , `docente_registro_num_doc` , `docente_registro_rol_id_rol` , `docente_registro_jornada_id_jornada`)
    REFERENCES `Edufast`.`docente` (`id_docente` , `cursos_id_cursos` , `cursos_grado_id_grado` , `registro_num_doc` , `registro_rol_id_rol` , `registro_jornada_id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_has_materia_materia1`
    FOREIGN KEY (`materia_id_materia` , `materia_grado_id_grado` , `materia_area_id_area`)
    REFERENCES `Edufast`.`materia` (`id_materia` , `grado_id_grado` , `area_id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
